POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0MzdhMjIzYTg3ZWI1MGEwNWFmODlhMyIsImlhdCI6MTY4MTUwMDMwNX0.9BtKpL5lQHG6eWVbpNFLaJ2QeoIofgO9zJJdEG-pjFk

{
    "title": "oooooooo",
    "author": "Berk",
    "url": "someurl",
    "likes": 3439
}
